#pragma once

namespace mnes::opcodes {

constexpr uint8_t OPCODE_ADC_OP = 0x69U;
constexpr uint8_t OPCODE_ADC_ZP = 0x65;
constexpr uint8_t OPCODE_ADC_ZP_X = 0x75;
constexpr uint8_t OPCODE_ADC_AB = 0x6D;
constexpr uint8_t OPCODE_ADC_AB_X = 0x7D;
constexpr uint8_t OPCODE_ADC_AB_Y = 0x79;
constexpr uint8_t OPCODE_ADC_IN_X = 0x61;
constexpr uint8_t OPCODE_ADC_IN_Y = 0x71;
constexpr uint8_t OPCODE_AND_OP = 0x29;
constexpr uint8_t OPCODE_AND_ZP = 0x25;
constexpr uint8_t OPCODE_AND_ZP_X = 0x35;
constexpr uint8_t OPCODE_AND_AB = 0x2D;
constexpr uint8_t OPCODE_AND_AB_X = 0x3D;
constexpr uint8_t OPCODE_AND_AB_Y = 0x39;
constexpr uint8_t OPCODE_AND_IN_X = 0x21;
constexpr uint8_t OPCODE_AND_IN_Y = 0x31;
constexpr uint8_t OPCODE_ASL_A = 0x0A;
constexpr uint8_t OPCODE_ASL_ZP = 0x06;
constexpr uint8_t OPCODE_ASL_ZP_X = 0x16;
constexpr uint8_t OPCODE_ASL_AB = 0x0E;
constexpr uint8_t OPCODE_ASL_AB_X = 0x1E;
constexpr uint8_t OPCODE_BCC = 0x90;
constexpr uint8_t OPCODE_BCS = 0xB0;
constexpr uint8_t OPCODE_BEQ = 0xF0;
constexpr uint8_t OPCODE_BIT_ZP = 0x24;
constexpr uint8_t OPCODE_BIT_AB = 0x2C;
constexpr uint8_t OPCODE_BMI = 0x30;
constexpr uint8_t OPCODE_BNE = 0xD0;
constexpr uint8_t OPCODE_BPL = 0x10;
constexpr uint8_t OPCODE_BRK = 0x00;
constexpr uint8_t OPCODE_BVC = 0x50;
constexpr uint8_t OPCODE_BVS = 0x70;
constexpr uint8_t OPCODE_CLC = 0x18;
constexpr uint8_t OPCODE_CLD = 0xD8;
constexpr uint8_t OPCODE_CLI = 0x58;
constexpr uint8_t OPCODE_CLV = 0xB8;
constexpr uint8_t OPCODE_CMP_OP = 0xC9;
constexpr uint8_t OPCODE_CMP_ZP = 0xC5;
constexpr uint8_t OPCODE_CMP_ZP_X = 0xD5;
constexpr uint8_t OPCODE_CMP_AB = 0xCD;
constexpr uint8_t OPCODE_CMP_AB_X = 0xDD;
constexpr uint8_t OPCODE_CMP_AB_Y = 0xD9;
constexpr uint8_t OPCODE_CMP_IN_X = 0xC1;
constexpr uint8_t OPCODE_CMP_IN_Y = 0xD1;
constexpr uint8_t OPCODE_CPX_OP = 0xE0;
constexpr uint8_t OPCODE_CPX_ZP = 0xE4;
constexpr uint8_t OPCODE_CPX_AB = 0xEC;
constexpr uint8_t OPCODE_CPY_OP = 0xC0;
constexpr uint8_t OPCODE_CPY_ZP = 0xC4;
constexpr uint8_t OPCODE_CPY_AB = 0xCC;
constexpr uint8_t OPCODE_DEC_ZP = 0xC6;
constexpr uint8_t OPCODE_DEC_ZP_X = 0xD6;
constexpr uint8_t OPCODE_DEC_AB = 0xCE;
constexpr uint8_t OPCODE_DEC_AB_X = 0xDE;
constexpr uint8_t OPCODE_DEX = 0xCA;
constexpr uint8_t OPCODE_DEY = 0x88;
constexpr uint8_t OPCODE_EOR_OP = 0x49;
constexpr uint8_t OPCODE_EOR_ZP = 0x45;
constexpr uint8_t OPCODE_EOR_ZP_X = 0x55;
constexpr uint8_t OPCODE_EOR_AB = 0x4D;
constexpr uint8_t OPCODE_EOR_AB_X = 0x5D;
constexpr uint8_t OPCODE_EOR_AB_Y = 0x59;
constexpr uint8_t OPCODE_EOR_IN_X = 0x41;
constexpr uint8_t OPCODE_EOR_IN_Y = 0x51;
constexpr uint8_t OPCODE_INC_ZP = 0xE6;
constexpr uint8_t OPCODE_INC_ZP_X = 0xF6;
constexpr uint8_t OPCODE_INC_AB = 0xEE;
constexpr uint8_t OPCODE_INC_AB_X = 0xFE;
constexpr uint8_t OPCODE_INX = 0xE8;
constexpr uint8_t OPCODE_INY = 0xC8;
constexpr uint8_t OPCODE_JMP_AB = 0x4C;
constexpr uint8_t OPCODE_JMP_IN = 0x6C;
constexpr uint8_t OPCODE_JSR_AB = 0x20;
constexpr uint8_t OPCODE_LDA_OP = 0xA9;
constexpr uint8_t OPCODE_LDA_ZP = 0xA5;
constexpr uint8_t OPCODE_LDA_ZP_X = 0xB5;
constexpr uint8_t OPCODE_LDA_AB = 0xAD;
constexpr uint8_t OPCODE_LDA_AB_X = 0xBD;
constexpr uint8_t OPCODE_LDA_AB_Y = 0xB9;
constexpr uint8_t OPCODE_LDA_IN_X = 0xA1;
constexpr uint8_t OPCODE_LDA_IN_Y = 0xB1;
constexpr uint8_t OPCODE_LDX_OP = 0xA2;
constexpr uint8_t OPCODE_LDX_ZP = 0xA6;
constexpr uint8_t OPCODE_LDX_ZP_Y = 0xB6;
constexpr uint8_t OPCODE_LDX_AB = 0xAE;
constexpr uint8_t OPCODE_LDX_AB_Y = 0xBE;
constexpr uint8_t OPCODE_LDY_OP = 0xA0;
constexpr uint8_t OPCODE_LDY_ZP = 0xA4;
constexpr uint8_t OPCODE_LDY_ZP_X = 0xB4;
constexpr uint8_t OPCODE_LDY_AB = 0xAC;
constexpr uint8_t OPCODE_LDY_AB_X = 0xBC;
constexpr uint8_t OPCODE_LSR_A = 0x4A;
constexpr uint8_t OPCODE_LSR_ZP = 0x46;
constexpr uint8_t OPCODE_LSR_ZP_X = 0x56;
constexpr uint8_t OPCODE_LSR_AB = 0x4E;
constexpr uint8_t OPCODE_LSR_AB_X = 0x5E;
constexpr uint8_t OPCODE_NOP = 0xEA;
constexpr uint8_t OPCODE_ORA_OP = 0x09;
constexpr uint8_t OPCODE_ORA_ZP = 0x05;
constexpr uint8_t OPCODE_ORA_ZP_X = 0x15;
constexpr uint8_t OPCODE_ORA_AB = 0x0D;
constexpr uint8_t OPCODE_ORA_AB_X = 0x1D;
constexpr uint8_t OPCODE_ORA_AB_Y = 0x19;
constexpr uint8_t OPCODE_ORA_IN_X = 0x01;
constexpr uint8_t OPCODE_ORA_IN_Y = 0x11;
constexpr uint8_t OPCODE_PHA = 0x48;
constexpr uint8_t OPCODE_PHP = 0x08;
constexpr uint8_t OPCODE_PLA = 0x68;
constexpr uint8_t OPCODE_PLP = 0x28;
constexpr uint8_t OPCODE_ROL_A = 0x2A;
constexpr uint8_t OPCODE_ROL_ZP = 0x26;
constexpr uint8_t OPCODE_ROL_ZP_X = 0x36;
constexpr uint8_t OPCODE_ROL_AB = 0x2E;
constexpr uint8_t OPCODE_ROL_AB_X = 0x3E;
constexpr uint8_t OPCODE_ROR_A = 0x6A;
constexpr uint8_t OPCODE_ROR_ZP = 0x66;
constexpr uint8_t OPCODE_ROR_ZP_X = 0x76;
constexpr uint8_t OPCODE_ROR_AB = 0x6E;
constexpr uint8_t OPCODE_ROR_AB_X = 0x7E;
constexpr uint8_t OPCODE_RTI = 0x40;
constexpr uint8_t OPCODE_RTS = 0x60;
constexpr uint8_t OPCODE_SBC_OP = 0xE9;
constexpr uint8_t OPCODE_SBC_IMM_EB = 0xEB;
constexpr uint8_t OPCODE_SBC_ZP = 0xE5;
constexpr uint8_t OPCODE_SBC_ZP_X = 0xF5;
constexpr uint8_t OPCODE_SBC_AB = 0xED;
constexpr uint8_t OPCODE_SBC_AB_X = 0xFD;
constexpr uint8_t OPCODE_SBC_AB_Y = 0xF9;
constexpr uint8_t OPCODE_SBC_IN_X = 0xE1;
constexpr uint8_t OPCODE_SBC_IN_Y = 0xF1;
constexpr uint8_t OPCODE_SEC = 0x38;
constexpr uint8_t OPCODE_SED = 0xF8;
constexpr uint8_t OPCODE_SEI = 0x78;
constexpr uint8_t OPCODE_STA_ZP = 0x85;
constexpr uint8_t OPCODE_STA_ZP_X = 0x95;
constexpr uint8_t OPCODE_STA_AB = 0x8D;
constexpr uint8_t OPCODE_STA_AB_X = 0x9D;
constexpr uint8_t OPCODE_STA_AB_Y = 0x99;
constexpr uint8_t OPCODE_STA_IN_X = 0x81;
constexpr uint8_t OPCODE_STA_IN_Y = 0x91;
constexpr uint8_t OPCODE_STX_ZP = 0x86;
constexpr uint8_t OPCODE_STX_ZP_Y = 0x96;
constexpr uint8_t OPCODE_STX_AB = 0x8E;
constexpr uint8_t OPCODE_STY_ZP = 0x84;
constexpr uint8_t OPCODE_STY_ZP_X = 0x94;
constexpr uint8_t OPCODE_STY_AB = 0x8C;
constexpr uint8_t OPCODE_TAX = 0xAA;
constexpr uint8_t OPCODE_TAY = 0xA8;
constexpr uint8_t OPCODE_TSX = 0xBA;
constexpr uint8_t OPCODE_TXA = 0x8A;
constexpr uint8_t OPCODE_TXS = 0x9A;
constexpr uint8_t OPCODE_TYA = 0x98;

constexpr uint8_t OPCODE_SLO_AB = 0x0F;
constexpr uint8_t OPCODE_SLO_AB_X = 0x1F;
constexpr uint8_t OPCODE_SLO_AB_Y = 0x1B;
constexpr uint8_t OPCODE_SLO_ZP = 0x07;
constexpr uint8_t OPCODE_SLO_ZP_X = 0x17;
constexpr uint8_t OPCODE_SLO_IN_X = 0x03;
constexpr uint8_t OPCODE_SLO_IN_Y = 0x13;

constexpr uint8_t OPCODE_RLA_AB = 0x2F;
constexpr uint8_t OPCODE_RLA_AB_X = 0x3F;
constexpr uint8_t OPCODE_RLA_AB_Y = 0x3B;
constexpr uint8_t OPCODE_RLA_ZP = 0x27;
constexpr uint8_t OPCODE_RLA_ZP_X = 0x37;
constexpr uint8_t OPCODE_RLA_IN_X = 0x23;
constexpr uint8_t OPCODE_RLA_IN_Y = 0x33;
// aka SRE;
constexpr uint8_t OPCODE_LSE_AB = 0x4F;
constexpr uint8_t OPCODE_LSE_AB_X = 0x5F;
constexpr uint8_t OPCODE_LSE_AB_Y = 0x5B;
constexpr uint8_t OPCODE_LSE_ZP = 0x47;
constexpr uint8_t OPCODE_LSE_ZP_X = 0x57;
constexpr uint8_t OPCODE_LSE_IN_X = 0x43;
constexpr uint8_t OPCODE_LSE_IN_Y = 0x53;
constexpr uint8_t OPCODE_RRA_AB = 0x6F;
constexpr uint8_t OPCODE_RRA_AB_X = 0x7F;
constexpr uint8_t OPCODE_RRA_AB_Y = 0x7B;
constexpr uint8_t OPCODE_RRA_ZP = 0x67;
constexpr uint8_t OPCODE_RRA_ZP_X = 0x77;
constexpr uint8_t OPCODE_RRA_IN_X = 0x63;
constexpr uint8_t OPCODE_RRA_IN_Y = 0x73;
constexpr uint8_t OPCODE_AXS_AB = 0x8F;
constexpr uint8_t OPCODE_AXS_ZP = 0x87;
constexpr uint8_t OPCODE_AXS_ZP_Y = 0x97;
constexpr uint8_t OPCODE_AXS_IN_X = 0x83;
constexpr uint8_t OPCODE_LAX_AB = 0xAF;
constexpr uint8_t OPCODE_LAX_AB_Y = 0xBF;
constexpr uint8_t OPCODE_LAX_ZP = 0xA7;
constexpr uint8_t OPCODE_LAX_ZP_Y = 0xB7;
constexpr uint8_t OPCODE_LAX_IN_X = 0xA3;
constexpr uint8_t OPCODE_LAX_IN_Y = 0xB3;
constexpr uint8_t OPCODE_DCP_AB = 0xCF;
constexpr uint8_t OPCODE_DCP_AB_X = 0xDF;
constexpr uint8_t OPCODE_DCP_AB_Y = 0xDB;
constexpr uint8_t OPCODE_DCP_ZP = 0xC7;
constexpr uint8_t OPCODE_DCP_ZP_X = 0xD7;
constexpr uint8_t OPCODE_DCP_IN_X = 0xC3;
constexpr uint8_t OPCODE_DCP_IN_Y = 0xD3;
// aka ISB;
constexpr uint8_t OPCODE_ISC_AB = 0xEF;
constexpr uint8_t OPCODE_ISC_AB_X = 0xFF;
constexpr uint8_t OPCODE_ISC_AB_Y = 0xFB;
constexpr uint8_t OPCODE_ISC_ZP = 0xE7;
constexpr uint8_t OPCODE_ISC_ZP_X = 0xF7;
constexpr uint8_t OPCODE_ISC_IN_X = 0xE3;
constexpr uint8_t OPCODE_ISC_IN_Y = 0xF3;
constexpr uint8_t OPCODE_ALR_IMM = 0x4B;
constexpr uint8_t OPCODE_ARR_IMM = 0x6B;
constexpr uint8_t OPCODE_XAA_IMM = 0x8B;
constexpr uint8_t OPCODE_OAL_IMM = 0xAB;
constexpr uint8_t OPCODE_AXS_IMM = 0xCB;
constexpr uint8_t OPCODE_NOP_1A = 0x1A;
constexpr uint8_t OPCODE_NOP_3A = 0x3A;
constexpr uint8_t OPCODE_NOP_5A = 0x5A;
constexpr uint8_t OPCODE_NOP_7A = 0x7A;
constexpr uint8_t OPCODE_NOP_DA = 0xDA;
constexpr uint8_t OPCODE_NOP_FA = 0xFA;
constexpr uint8_t OPCODE_NOP_1C_AB_X = 0x1C;
constexpr uint8_t OPCODE_NOP_3C_AB_X = 0x3C;
constexpr uint8_t OPCODE_NOP_5C_AB_X = 0x5C;
constexpr uint8_t OPCODE_NOP_7C_AB_X = 0x7C;
constexpr uint8_t OPCODE_NOP_DC_AB_X = 0xDC;
constexpr uint8_t OPCODE_NOP_FC_AB_X = 0xFC;
constexpr uint8_t OPCODE_NOP_14_ZP_X = 0x14;
constexpr uint8_t OPCODE_NOP_34_ZP_X = 0x34;
constexpr uint8_t OPCODE_NOP_54_ZP_X = 0x54;
constexpr uint8_t OPCODE_NOP_74_ZP_X = 0x74;
constexpr uint8_t OPCODE_NOP_D4_ZP_X = 0xD4;
constexpr uint8_t OPCODE_NOP_F4_ZP_X = 0xF4;

constexpr uint8_t OPCODE_NOP_04_ZP = 0x04;
constexpr uint8_t OPCODE_NOP_44_ZP = 0x44;
constexpr uint8_t OPCODE_NOP_64_ZP = 0x64;

// missing for sure:
constexpr uint8_t OPCODE_SHY_AB_X = 0x9C;
constexpr uint8_t OPCODE_SHX_AB_Y = 0x9E;

constexpr uint8_t OPCODE_TAS_AB_Y = 0x9B;
constexpr uint8_t OPCODE_LAS_AB_Y = 0xBB;
constexpr uint8_t OPCODE_AHX_AB_Y = 0x9F;
constexpr uint8_t OPCODE_AHX_IN_Y = 0x93;

constexpr uint8_t OPCODE_NOP_IMM = 0x80;
constexpr uint8_t OPCODE_NOP_IMM_82 = 0x82;
constexpr uint8_t OPCODE_NOP_IMM_89 = 0x89;
constexpr uint8_t OPCODE_NOP_IMM_C2 = 0xC2;
constexpr uint8_t OPCODE_NOP_IMM_E2 = 0xE2;
constexpr uint8_t OPCODE_ANC_IMM_0B = 0x0B;
constexpr uint8_t OPCODE_ANC_IMM_2B = 0x2B;
constexpr uint8_t OPCODE_LAX_IMM = 0xAB;

constexpr uint8_t OPCODE_SAX_ZP = 0x87;
constexpr uint8_t OPCODE_SAX_ZP_Y = 0x97;

}// namespace mnes::opcodes

struct SDebugOpCode
{
  const char *sOpCode;
  int nParams;
  int nType;
};

struct SDebugOpCodeFormat
{
  const char *pcszFormat;
};

extern SDebugOpCode OpCodes[256];
extern SDebugOpCodeFormat OpCodeFormats[13];
